### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced!

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /stories/assets/bmo.png | 19.64kb | 17.21kb | 12.40% |
| /.storybook/compressed-logo-rbd.svg | 3.74kb | 3.62kb | 3.24% |
| /stories/assets/jake.png | 9.43kb | 9.28kb | 1.64% |
| /stories/assets/princess.png | 21.28kb | 21.13kb | 0.68% |
| /stories/assets/finn.png | 17.58kb | 17.47kb | 0.63% |
| | | | |
| **Total :** | **71.67kb** | **68.70kb** | **4.14%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by MichaelDeBoey** [comment]
Hi Alex!

Any reason why you won't add this bot to the repo?

It's not my bot, but I came across it and thought it's an awesome bot that helps you with image optimization without thinking about it and would be useful in my opinion 🙂

**Comment by alexreardon** [comment]
Hey, I wasn't sure if this was spam. Let's reopen this

**Comment by MichaelDeBoey** [comment]
No this isn't spam, just want to help out that's all 🙂

**Comment by alexreardon** [comment]
No need to close this issue! Happy to get the improvements in

**Comment by MichaelDeBoey** [comment]
@alexreardon There were merge conflicts, so the only way to solve these is to close and create a new PR (see dabutvin/Imgbot#352), which is #1567

**Pull request closed without merging**
