### PR TITLE
Upgrade to babel 7

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by alexreardon** [comment]
> /home/circleci/repo/babel.config.js
  1:1  error  Flow file annotation is missing  flowtype/require-valid-file-annotation

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

**Comment by TrySound** [comment]
Would be good to publish it with the patch.

**Comment by alexreardon** [comment]
👍

**Comment by alexreardon** [comment]
I will aim to do a patch release tomorrow

**Pull request merged**
