### PR TITLE
Updated peerDependencies to react@^18

### PR DESCRIPTION
**Pull request by jankanty**
It solves:
#2416
#2426
#2428

Can we merge it and release new version to npm? I looked at all changes since last release and they were pure documentation.

### CODE REVIEW

**Comment by jankanty** [comment]
@danieldelcore can you look at circleci and help it pass? Looks like random fail

**Comment by stianberg** [comment]
Any news on this? :)

**Comment by wladiston** [comment]
I'm already using it in production and seems to be working fine. No reason why it should be hold back

**Comment by esslamben** [comment]
Any updates on this?

**Comment by kaby2201** [comment]
Seems there is no approval at the moment, I added the peer dependencies and published it at
https://www.npmjs.com/package/react-beautiful-dnd-ledger

**Comment by danieldelcore** [comment]
Hey folks, thanks for your patience on this. Let's merge this one 👍

**Comment by jankanty** [comment]
@danieldelcore would you release new npm version also? Or its done automatically.

**Comment by oskarwrobel** [comment]
@jankanty looks like it's done.

**Comment by danieldelcore** [comment]
Yep should be good to go, please lmk if it doesn't work

**Comment by esslamben** [comment]
Just bumped up the version and all is working. Thank you very much @jankanty @danieldelcore.

**Pull request merged**
