### PR TITLE
Export default sensors

### LINKED ISSUE #1698: Please export the default sensors from the npm package
### Description
I am creating a drag-and-drop interaction where the end users will either use a mouse or a touch screen. Keyboard/screenreaders have a different interaction where they get to click the destination lists to move the item from the starting position to the ending position. I would like a way to basically just implement the 2 sensor APIs that I want, while leaving the Keyboard sensor API effectively disabled. But I can't do that the way the NPM package is published. The sensor hooks are not part of the export, and there isn't a way to import them from a standalone file either.

e.g. `<DragDropContext sensors={[useMouseSensor, useTouchSensor]} enableDefaultSensors={false} />`

### PR DESCRIPTION
**Pull request by vladmoroz**
Export default sensors and update the docs. Based on #1705 as I noticed the feedback wasn't addressed in the original PR for a while.

Fixes #1698.

### CODE REVIEW

**Comment by fnpen** [comment]
I am waiting for it, I hope it will be released soon.

**Comment by tedgoddard** [comment]
@danieldelcore Please merge this PR (and any other PRs deemed suitable) and provide another release (it has been a year). This is an outstanding library, but people will either need to fork this project or stop using it if it's not maintained.

**Comment by danieldelcore** [comment]
Hey folks 👋 

Many apologies for the delay on this one! Thanks so much for taking the time to comment & contribute 👍  and thanks for pinging me to let me know!

Changes look good to me 👍 👍 👍 👍 👍  Expect a release either today or tomorrow!

**Review by danieldelcore — APPROVED** [review]

**Comment by danieldelcore** [comment]
Just cut a new release for this! Thanks a lot  @vladmoroz, @tedgoddard, @fnpen, @nerdkid93🎉 !

https://github.com/atlassian/react-beautiful-dnd/releases/tag/v13.1.0

Let me know how it goes 😄

**Comment by Simonlfr** [comment]
Hello,
This is a great change. But, it seems that react-beautiful-dnd is one version ahead of @types/react-beautiful-dnd, so these types are just not served for typescript. @danieldelcore

**Pull request merged**
