### PR TITLE
Emotion again

### PR DESCRIPTION
**Pull request by alexreardon**

### CODE REVIEW

**Comment by varHarrie** [comment]
Why `Emotion`? Just be curious.

**Comment by alexreardon** [comment]
> Why `Emotion`? Just be curious.

There is almost nothing between them. We are thinking of consolidating internally on emotion and I wanted to give it a go for a while.

Longer answer: 

- performance: similar
- kbs: emotion is a bit smaller (not super important for our doc site)
- emotion has a more flexible api which can help us achieve behaviours that are harder with styled-components
- emotion has a cleaner SSR story
- emotion has a styled.div syntax so you can use it exactly the same and you would styled-components. This also allows for a simpler rollback path.

Given it was so easy to change, we might change back in the future too

**Comment by alexreardon** [comment]
moving to emotion again

**Comment by varHarrie** [comment]
Thank for your clear explanation. I am a heavy user for `styled-components` and a defector of `emotion`. I had forgotten the reason since they are too similar.

**Pull request merged**
