### PR TITLE
update to babel-preset-env

### PR DESCRIPTION
**Pull request by alirezavalizade**

### CODE REVIEW

**Comment by alexreardon** [comment]
We support a [range of browers]. We would need to instruct babel-preset-env about what browsers we are using using a browserlist. We could not just use the default.

Given that we support ie11 using babel-preset-2015 is sufficient for now. However, I am happy to proceed with this if you are willing to add the correct browser list 👍

**Comment by alirezavalizade** [comment]
@alexreardon Please check [this](https://github.com/atlassian/react-beautiful-dnd/pull/325/commits/92b333bd9bb23db49db6a211f589bfcc81a50165).

**Comment by alexreardon** [comment]
Hi @alirezavalizade, I think it is better to be a little more explicit to match our browser matrix. Here is what we are using in other products:

```
ie >= 11
last 1 Edge version
last 1 Firefox version
last 1 Chrome version
last 1 Safari version
last 1 iOS version
last 1 Android version
last 1 ChromeAndroid version
```
If you can add that we should be good to go!

**Comment by alirezavalizade** [comment]
@alexreardon Hi, Great.
Thanks browser matrix!

**Comment by alexreardon** [comment]
I'll check this tomorrow and ensure it is working correctly

Then we should be gewd

**Comment by alexreardon** [comment]
I have not forgotten about this. I am just focusing on the moment on shipping #321. I hope to merge this for 5.0

**Comment by alexreardon** [comment]
Whoops - i think i messed this up by trying to add a commit

**Comment by alirezavalizade** [comment]
Thanks.

**Pull request closed without merging**
