### PR TITLE
more robust typeof element checks

### PR DESCRIPTION
**Pull request by alexreardon**
Closes #797 #796

### CODE REVIEW

**Comment by alexreardon** [comment]
I figured out a way to do this without relying on duck typing 👍👍👍

Maintaining the same type safely while allowing iframes

wow-jake

**Comment by alexreardon** [comment]
cc @jdillick @vladkucherov @SenyaMur

**Comment by SenyaMur** [comment]
Thank you! When you will publish this solution?

**Comment by alexreardon** [comment]
Soon 🤞

**Pull request merged**
