### PR TITLE
Allow combine without reordering

### PR DESCRIPTION
**Pull request by GDIBass**
Implements: Issue #1390

This mostly piggybacks off of what @mattkrick started here: https://github.com/atlassian/react-beautiful-dnd/pull/1460 , except I believe I've fixed the testing issues.

I'm not well versed in Jest, so I haven't built out any tests yet.  If anyone can help with that let me know, otherwise I'm going to give it a shot tomorrow.

### CODE REVIEW

**Comment by DanielPower** [comment]
Sorry if I'm missing something obvious, but could you tell me how test your branch? I've pulled it down with `npm i GDIBass/react-beautiful-dnd#is-combine-only`, but the resulting `node_modules/react-beautiful-dnd` does not contain a dist directory. Just src and 

I'm not familiar with the build process. Is there a command I need to run to generate the dist directory?

**Comment by GDIBass** [comment]
@DanielPower my own testing process was as follows:

1. Install the package on a project of mine
2. Download this repo
3. Run yarn install
4. run yarn build
5. Copy the dist/src files to node_modules on my own project
6. Build my project
7. Test ahoy.

I'm pretty sure there's a better way to do it using the tarball method here, but the way I did it was decently easy.   https://github.com/atlassian/react-beautiful-dnd/pull/1460

I haven't had a chance to look into building out more tests to cover these, but I will shortly.  I don't think tonight, but likely over the weekend.

**Comment by DanielPower** [comment]
Thanks for the instructions, that worked perfectly. I didn't know about yarn until now. Also a minor suggestion, you could simply symlink your node_modules/react-beautiful-dnd/dist directory to the dist directory in your build directory, to save you from having to re-copy every time.

As for the PR, I just tested it out, and it's really close! But there's a bit of an issue with it (unless I'm doing something wrong). Attached is a gif of me attempting to use `isCombineOnly`.

As you can see, although reordering is disabled, the space that was taken up by the item being dragged does get filled in, and it seems the position of items do not get updated in the combine logic. 

video of issue

**Comment by GDIBass** [comment]
Good find.  I'll take a look at that over the weekend.

Definitely would like @alexreardon 's input there.  I personally like the "isCombineOnly" prop, because it's intuitive to use.

**Comment by ArielFrischer** [comment]
Would love to see this implemented I've tried multiple workarounds in other issues to no avail because placeholder seems to keep moving around behind the scenes. Any updates on whether this will get merged?

**Comment by dannywitters** [comment]
any updates on when this might get merged?

**Comment by MichielMortier** [comment]
Could this be merged?

**Comment by spideyboy18** [comment]
When will it be merged?

**Comment by GDIBass** [comment]
I ended up abandoning this for a different solution.  If anyone wants to pick it up and run with it, feel free.  As is it definitely doesn't pass all required tests.

**Comment by matheusAle** [comment]
any update about this?

**Comment by ariel-frischer** [comment]
> I ended up abandoning this for a different solution. If anyone wants to pick it up and run with it, feel free. As is it definitely doesn't pass all required tests.

Can you explain the new solution you have used?

**Comment by GDIBass** [comment]
For my use case I ended up setting up individual drop containers for each of the slots, so instead of doing

drop container with items: [a, b, c, d, e]

I ended up with:
[a] [b] [c] [d] [e]

You'd drag from e to a, then I'd update the a drop container with e

[ae] [b] [c] [d] []

May not work for everybody but for my use case it got the job done pretty well

**Comment by ariel-frischer** [comment]
> For my use case I ended up setting up individual drop containers for each of the slots, so instead of doing
> 
> drop container with items: [a, b, c, d, e]
> 
> I ended up with:
> [a] [b] [c] [d] [e]
> 
> You'd drag from e to a, then I'd update the a drop container with e
> 
> [ae] [b] [c] [d] []
> 
> May not work for everybody but for my use case it got the job done pretty well

Sounds good thanks!

**Pull request closed without merging**
