### PR TITLE
Add typescript types into repo

### PR DESCRIPTION
**Pull request by benhjames**
A nice first step toward TypeScript support (#982) would be to move the typings from DefinitelyTyped into this repo. This PR does just that! 🎉

### CODE REVIEW

**Comment by alexreardon** [comment]
This seems like a reasonable short term solution

**Comment by alexreardon** [comment]
Are the types from the existing @types repo?

**Comment by benhjames** [comment]
Yep, it's an exact copy paste with the exception of 4 spaces -> 2 spaces indentation.

Ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-beautiful-dnd/index.d.ts

**Comment by alexreardon** [comment]
For now I will hold off this one as the plan is to move the whole project over to typescript #982

**Pull request closed without merging**
