### PR TITLE
Dynamically adding area to foreign list when dragging over

### PR DESCRIPTION
**Pull request by woohling**
#77 
I'm fixing this issue by adding extra area when dragging over foreign list. I hope I'm fixing it right.

### CODE REVIEW

**Comment by alexreardon** [comment]
This increase is already achieved but the `withPlaceholder` function 👍

**Comment by alexreardon** [comment]
Thanks for being the change you seek :)

**Comment by woohling** [comment]
I know with placeholder can increase the droppable space.  My update is for when the droppable height is fixed and the last one on the list is quite hard to target at. 

For example, when I drag an item over the list on item 12 and want to put the item behind it, the hit rate is quite low, cause the active area is the height of the list before dragging start. What I'm proposed is to increase the active area when dragging over the list, thus I can easily put the dragging item on the last spot of thelist.
xnip2018-12-03_13-29-49

**Comment by woohling** [comment]
@alexreardon I'm closing this Pull Request cause I found that it will cause bugs in some scenario. More scenarios need to be taken into control, I'm still too careless

**Pull request closed without merging**
