### PR TITLE
Updating README remove note about polyfill for IE 11

### PR DESCRIPTION
**Pull request by wuweiweiwu**
As of release v10 the `Array.prototype.find` polyfill for IE 11 is no longer needed

see: https://github.com/atlassian/react-beautiful-dnd/issues/724#issuecomment-439733509

### CODE REVIEW

**Comment by alexreardon** [comment]
🤘

**Comment by petermikitsh** [comment]
I'm using the `v12.0.0-alpha.1` release and I've found that the `Array.prototype.fill` polyfill is needed for IE 11.

**Comment by alexreardon** [comment]
Really? I cannot find the usage. This might be changed in the next alpha

**Comment by petermikitsh** [comment]
If it's any help, here's a screenshot of where the exception is thrown.

Screen Shot 2019-06-17 at 6 43 48 PM

**Comment by petermikitsh** [comment]
Looks like it's in the `getDragHandler` function.

Screen Shot 2019-06-17 at 6 48 15 PM

**Comment by petermikitsh** [comment]
Found it here: https://github.com/atlassian/react-beautiful-dnd/blob/virtual/src/view/use-focus-marshal/use-focus-marshal.js#L33

**Comment by alexreardon** [comment]
Perfect! I will remove this

**Comment by alexreardon** [comment]
This has shipped in `12.0.0-alpha.3`

**Pull request merged**
