### PR TITLE
add isCombineOnly alternative to isCombineEnabled

### LINKED ISSUE #1390: Allow combining without reordering

### PR DESCRIPTION
**Pull request by mattkrick**
Fixes #1390
simply pass `isCombineOnly` instead of `isCombineEnabled` to turn off reordering.

### CODE REVIEW

**Comment by GDIBass** [comment]
@mattkrick @alexreardon looks like this had a few test fail.  Anything me (or someone else) can do to help push this forward?

**Comment by mattkrick** [comment]
@GDIBass sorry i let this go stale, i've since gone with another solution & don't need the PR to land.

feel free to clone my PR & champion it forward, or if you fix the tests on the branch, feel free to ping me & i'll merge them!

In the meantime, you can play with it today by swapping out the version in your package.json with the following: `https://github.com/mattkrick/react-beautiful-dnd/tarball/d9a783c8d766ad21144c9db8a774ebc68f5dd39b`

if there's anything else i can do to help, lemme know.

**Comment by GDIBass** [comment]
No worries, thanks for the FYI.  I'll probably put some work into it tonight!

**Comment by mattkrick** [comment]
closed in favor of #1505

**Pull request closed without merging**
